### ISSUE TITLE
error compiling during npm install sodium-native

### ISSUE THREAD

**Issue by naknomum** [holepunchto/sodium-native#56]
trying to install this on my linux box tonight, compiling fails.  i believe this is the relevant section of the **npm-debug.log**:

```
make: Entering directory `/usr/lib/node_modules/sodium-native/build'
  CXX(target) Release/obj.target/sodium/binding.o
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:547:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash_str(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:558:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash_str_verify(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:567:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash_async(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:583:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash_str_async(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:606:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_pwhash_str_verify_async(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:624:3: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../binding.cc: In function ‘void InitAll(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../binding.cc:954:3: error: ‘UINT64_MAX’ was not declared in this scope
make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/sodium-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/sodium-native
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "sodium-native"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! sodium-native@2.1.2 install: `node-gyp-build "node preinstall.js" "node postinstall.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium-native@2.1.2 install script 'node-gyp-build "node preinstall.js" "node postinstall.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build "node preinstall.js" "node postinstall.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log

```

thanks!

**Comment by emilbayes** [comment]
@naknomum I have an idea why this happens. Can you clone this repo and try the `compiled-constants` branch?

```sh
git clone --recursive git://github.com/sodium-friends/sodium-native
cd sodium-native
git checkout compiled-constants
npm install
npm test
```

**Comment by naknomum** [comment]
sorry.... no such luck, @emilbayes ... getting same error:
```
../binding.cc:1032:3: error: ‘UINT64_MAX’ was not declared in this scope
make: *** [Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory `/tmp/s2/sodium-native/build'

$ git status
# On branch compiled-constants
```

googling around for this constant in particular, i found some potential(?) clues.... http://filoxus.blogspot.com/2009/07/limits-in-stdinth.html

https://stackoverflow.com/questions/3233054/error-int32-max-was-not-declared-in-this-scope

fwiw, this is indeed a vm in google cloud.

**Comment by emilbayes** [comment]
@naknomum I'm thinking that it may actually have worked (or at least the line numbers changed). I'm pretty sure it traces like this:

* https://github.com/sodium-friends/sodium-native/blob/14dabf7610175e178faed2c9a1b7efdfbffe40e3/binding.cc#L954
* https://github.com/jedisct1/libsodium/blob/675149b9b8b66ff44152553fb3ebf9858128363d/src/libsodium/include/sodium/crypto_pwhash.h#L33
* https://github.com/jedisct1/libsodium/blob/675149b9b8b66ff44152553fb3ebf9858128363d/src/libsodium/include/sodium/crypto_pwhash_argon2id.h#L25
* https://github.com/jedisct1/libsodium/blob/65f71fe06079eb1565d06d6afbe3423fb7f901cf/src/libsodium/include/sodium/export.h#L51

But what is happening here is that `libsodium` is compiled separately from the `sodium-native` bindings, and therefore works. Instead what I tried to have you test is to use the values that `libsodium` compiles with instead of the ones that are exposed in header files. I will try updating all the constants and maybe you can try compiling again? I will also see if I can get access to a google cloud vm so I can debug

**Comment by emilbayes** [comment]
@naknomum Can I get you to try again? I just replaced all official libsodium constants with their compiled accessors, which I think is also the right thing to do

**Comment by naknomum** [comment]
@emilbayes full success!  compiled and all tests passed.   thanks so much for the attention on this.

**Comment by emilbayes** [comment]
@naknomum Thanks for bringing this to our attention. Will do a release soon with fixes!

**Comment by emilbayes** [comment]
This will be released as `2.1.4`

**Comment by hackergrrl** [comment]
Hey @emilbayes will 2.1.4 be published to npm soon? I'm getting this issue too.

**Comment by emilbayes** [comment]
@noffle Woops, forgot to move the dist tag. Try now

**Comment by hackergrrl** [comment]
thank you!
