### PR TITLE
Fix compile on Node 12.6.0

### LINKED ISSUE #95: Build Error / Prebuilds for Node 12
I'm getting this when trying to build:

In file included from ../src/crypto_pwhash_async.cc:2:0,
                 from ../binding.cc:12:
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE crypto_secretstream_xchacha20poly1305_rekey(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:123:60: error: no matching function for call to ‘v8::Value::ToObject()’
   type* var = Nan::ObjectWrap::Unwrap<type>(name->ToObject());

### PR DESCRIPTION
**Pull request by davedoesdev**
Tests pass for me locally
Fixes #95

### CODE REVIEW

**Comment by mafintosh** [comment]
Thanks! @davedoesdev see you did a few changes to this recently - is this ready for review?

**Comment by davedoesdev** [comment]
@mafintosh yes ready for review now

File: binding.cc [hunk 1]
```diff
@@ -542,9 +542,9 @@ NAN_METHOD(crypto_generichash_instance) {
   unsigned long long output_length = crypto_generichash_bytes();
 
   if (info[1]->IsObject()) {
-    output_length = CLENGTH(info[1]->ToObject());
+    output_length = CLENGTH(info[1]->ToObject(v8::Isolate::GetCurrent()->GetCurrentContext()).ToLocalChecked());
```
Comment (emilbayes) [inline binding.cc]: Looking at this code now I think it is questionable of us to silently ignore a given arg that we don't understand how to interpret instead of silently carry on. Anyway, not entirely relevant to this :)

What do you think about making this line `output_length = CLENGTH(Nan::To<v8::Object>(info[1]).ToLocalChecked());`? I don't know what the original `ToLocalChecked()` does if there is an exception pending in contrast to the new `Maybe*` types

File: binding.cc [hunk 2]
```diff
@@ -542,9 +542,9 @@ NAN_METHOD(crypto_generichash_instance) {
...
   } else if (info[1]->IsNumber()) {
-    output_length = info[1]->Uint32Value();
+    output_length = info[1].As<v8::Uint32>()->Value();
```
Comment (emilbayes) [inline binding.cc]: Something similar could be said here: `output_length = Nan::To<uint32_t>(info[1]).FromJust();` (perhaps with a `IsJust()` check. Curious about the differences if you know?

File: src/crypto_generichash_wrap.cc [hunk 3]
```diff
@@ -41,7 +41,7 @@ v8::Local<v8::Value> CryptoGenericHashWrap::NewInstance (unsigned char *key, uns
   v8::Local<v8::Object> instance;
 
   v8::Local<v8::FunctionTemplate> constructorHandle = Nan::New<v8::FunctionTemplate>(crypto_generichash_constructor);
-  instance = Nan::NewInstance(constructorHandle->GetFunction()).ToLocalChecked();
+  instance = Nan::NewInstance(constructorHandle->GetFunction(v8::Isolate::GetCurrent()->GetCurrentContext()).ToLocalChecked()).ToLocalChecked();
```
Comment (emilbayes) [inline src/crypto_generichash_wrap.cc]: How about this? `instance = Nan::NewInstance(Nan::GetFunction(constructorHandle).ToLocalChecked()).ToLocalChecked();`

Just found it in the Nan test to see how they do it now https://github.com/nodejs/nan/blob/e222068f9d99967897a8cefa6c505534b36116ad/test/cpp/namedinterceptors.cpp#L58-L66

File: src/macros.h [hunk 4]
```diff
@@ -81,7 +81,7 @@
     Nan::ThrowError(#var " must be a number"); \
     return; \
   } \
-  int64_t var = name->IntegerValue(); \
+  int64_t var = name.As<v8::Number>()->Value(); \
```
Comment (emilbayes) [inline src/macros.h:84]: Is this equivalent to what was previously here? I can't tell from the v8 docs

**Review by emilbayes — COMMENTED** [review]
Thank you for all your work @davedoesdev! We had actually shelfed this version of sodium-native to work on the nan version instead. I've left quite a number of comments. Hope to get you opinion on this :)

**Comment by davedoesdev** [comment]
Hi @emilbayes I've not used nan in my projects, just modified it in others. I'm using https://github.com/nodejs/node-addon-api, I like it. Is using node-addon-api too much of a rewrite?

File: src/macros.h (hunk 4 above)
Comment (davedoesdev) [reply src/macros.h:84]: We've only tested for `IsNumber()` so I don't think we can assume it's an integer.
`Value()` will return a `double` (https://v8docs.nodesource.com/node-0.8/d9/d29/classv8_1_1_number.html), which will then get cast in C++ land to `int64_t`.

Unless I'm wrong of course!

File: binding.cc (hunk 2 above)
Comment (davedoesdev) [reply binding.cc]: Since we're checking `IsNumber`, we can do `output_length = info[1].As<v8::Number>()->Value();` here too. Otherwise this will have to change to checking for integer.

Comment (davedoesdev) [reply binding.cc]: Btw, the Nan docs seem to do `double value = info[0]->IsNumber() ? Nan::To<double>(info[0]).FromJust() : 0;`
I guess it's a matter of taste whether you need to go through a `Maybe`.

**Comment by davedoesdev** [comment]
@emilbayes  I've pushed some changes to address your comments. Not sure how correct they are - I'm not a Nan expert.

**Comment by soatok** [comment]
This fixed a compile issue I was running into after upgrading to Node 12 and Electron 5.

**Comment by soatok** [comment]
Is there anything I can help with to unstick this?

File: binding.cc (hunk 2 above)
Comment (emilbayes) [reply binding.cc]: But if we want to preserve previous behaviour it should be a uint32_t no?

File: src/macros.h (hunk 4 above)
Comment (emilbayes) [reply src/macros.h:84]: What happened here before was that it only returned the integer part, which had the implicit consequence that uint32 is much smaller than the largest buffer size

File: binding.cc (hunk 1 above)
Comment (emilbayes) [reply binding.cc]: @davedoesdev what do you think about the above suggestion?

**Comment by emilbayes** [comment]
@soatok we should resolve the above comments, ie. get clarity that previous behaviour is preserved :)

**Comment by davedoesdev** [comment]
I did push changes to address your comments. Can I leave comparison with previous behaviour to you?

**Comment by mafintosh** [comment]
Fixed the last parts of this and merged into master
